// SPDX-License-Identifier: Apache-2.0

//! Lightweight scan node for Lance datasets.

use std::any::Any;
use std::sync::Arc;

use datafusion::arrow::datatypes::SchemaRef as ArrowSchemaRef;
use datafusion::error::{DataFusionError, Result as DFResult};
use datafusion::execution::{SendableRecordBatchStream, TaskContext};
use datafusion::physical_plan::{DisplayAs, ExecutionPlan, PlanProperties};
use datafusion::prelude::Expr;
use lance::dataset::Dataset;

use crate::error::to_datafusion_error;

/// Scan node that delegates to Lance's `Scanner` planning.
///
/// This execution plan is a thin wrapper around the physical plan
/// produced by `lance::dataset::scanner::Scanner::create_plan`.
/// It preserves a friendly display name while reusing Lance's
/// internal planning for projection / filter / limit pushdown and
/// partitioning.
#[derive(Debug)]
pub struct LanceTableScan {
    /// Fully planned scan generated by Lance's Scanner.
    plan: Arc<dyn ExecutionPlan>,
    /// Logical projection indices from the DataFusion planner.
    projection: Option<Vec<usize>>,
    /// Logical filters that were pushed down.
    filters: Vec<Expr>,
    /// Optional row limit pushed down from the planner.
    limit: Option<usize>,
}

impl LanceTableScan {
    pub async fn try_new(
        dataset: Arc<Dataset>,
        schema: ArrowSchemaRef,
        projection: Option<&Vec<usize>>,
        filters: &[Expr],
        limit: Option<usize>,
    ) -> DFResult<Self> {
        let mut scanner = dataset.scan();

        // Apply projection pushdown by mapping indices back to column names.
        if let Some(cols) = projection {
            let names: Vec<String> = cols
                .iter()
                .map(|i| schema.field(*i).name().clone())
                .collect();

            scanner.project(&names).map_err(to_datafusion_error)?;
        }

        // Combine filters with AND and forward as a DataFusion expression.
        if !filters.is_empty() {
            let mut iter = filters.iter().cloned();
            if let Some(first) = iter.next() {
                let combined = iter.fold(first, Expr::and);
                scanner.filter_expr(combined);
            }
        }

        // Push down the limit when present. Offset is currently not used.
        if let Some(n) = limit {
            scanner
                .limit(Some(n as i64), None)
                .map_err(to_datafusion_error)?;
        }

        // Let Lance build the full physical plan, including any internal
        // filter / projection / limit pushdown and partitioning.
        let plan = scanner.create_plan().await.map_err(to_datafusion_error)?;

        Ok(Self {
            plan,
            projection: projection.cloned(),
            filters: filters.to_vec(),
            limit,
        })
    }
}

impl ExecutionPlan for LanceTableScan {
    fn name(&self) -> &str {
        "LanceTableScan"
    }

    fn as_any(&self) -> &dyn Any {
        self
    }

    fn schema(&self) -> ArrowSchemaRef {
        self.plan.schema()
    }

    fn properties(&self) -> &PlanProperties {
        self.plan.properties()
    }

    fn children(&self) -> Vec<&Arc<dyn ExecutionPlan>> {
        vec![&self.plan]
    }

    fn with_new_children(
        self: Arc<Self>,
        mut children: Vec<Arc<dyn ExecutionPlan>>,
    ) -> DFResult<Arc<dyn ExecutionPlan>> {
        if children.len() != 1 {
            return Err(DataFusionError::Internal(
                "LanceTableScan expects exactly one child".to_string(),
            ));
        }

        Ok(Arc::new(LanceTableScan {
            plan: children.remove(0),
            projection: self.projection.clone(),
            filters: self.filters.clone(),
            limit: self.limit,
        }))
    }

    fn execute(
        &self,
        partition: usize,
        context: Arc<TaskContext>,
    ) -> DFResult<SendableRecordBatchStream> {
        self.plan.execute(partition, context)
    }
}

impl DisplayAs for LanceTableScan {
    fn fmt_as(
        &self,
        _t: datafusion::physical_plan::DisplayFormatType,
        f: &mut std::fmt::Formatter,
    ) -> std::fmt::Result {
        write!(
            f,
            "LanceTableScan projection:[{}] limit:[{}]",
            self.projection
                .as_ref()
                .map(|v| {
                    v.iter()
                        .map(ToString::to_string)
                        .collect::<Vec<_>>()
                        .join(",")
                })
                .unwrap_or_default(),
            self.limit
                .map(|v| v.to_string())
                .unwrap_or_else(|| "none".to_string())
        )
    }
}
